version: '3.8'

services:
  langchain-assistant:
    build: ./LangChainAssistant
    ports:
      - "8000:8000"
    volumes:
      - /mnt/user/LangChainAssistant:/app
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_GPT=false
    restart: unless-stopped
